"""empty message

Revision ID: e4d95e5cac23
Revises: dd0add1fef94
Create Date: 2019-09-06 10:22:37.609143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d95e5cac23'
down_revision = 'dd0add1fef94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('new', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
